### ISSUE TITLE
Josev is broken after the latest update 

### ISSUE THREAD

**Issue by ziyadtarek7** [EVerest/ext-switchev-iso15118#27]
I want I try to run josev, I get this error:

> ImportError: cannot import name 'EVSessionContext' from 'iso15118.secc.controller.interface' (/home/zizou/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/secc/controller/interface.py)

the EVSessionContext was moved to another file, but even after fixing this error, I keep getting more and more error whenever I try to run it

@SebaLukas

**Comment by SebaLukas** [comment]
Hi :)

unfortunately we stopped the support for the SECC side of Josev a few weeks ago and only use Josev EVCC for our EVSimulation in Everest.

For the SECC side we use the EVerest module EvseV2G. It supports DIN70121 & ISO15118-2 (AC/DC EIM & PnC). You are welcome to try this C/C++ module. In the current main branch of everest-core you will find various config-sil yamls in the config folder in which the EvseV2G module is configured instead of PyJosev.

**Comment by ziyadtarek7** [comment]
> Hi :)
> 
> unfortunately we stopped the support for the SECC side of Josev a few weeks ago and only use Josev EVCC for our EVSimulation in Everest.
> 
> For the SECC side we use the EVerest module EvseV2G. It supports DIN70121 & ISO15118-2 (AC/DC EIM & PnC). You are welcome to try this C/C++ module. In the current main branch of everest-core you will find various config-sil yamls in the config folder in which the EvseV2G module is configured instead of PyJosev.

Thank you for the reply,
So currently ISO15118-20 isn't supported, right?

**Comment by SebaLukas** [comment]
We are currently supporting ISO15118-20 (DC, DC_BPT, Scheduled Mode & EIM only) in a beta state. We have written our own [C++ library](https://github.com/Everest/libiso15118/) for this purpose.
